# Colors
DARK_GREEN = '#005432'
LIGHT_GREEN = '#006747'
LIGHT_GOLD = '#CFC493'
SAND = '#EDEBD1'
GREY = '#EDF0F1'
STORM = '#006484'
APPLE = '#9CCB3B'
TEAL = '#009374'
SLATE = '#466069'
LEMON = '#DBE442'
SEAGLASS = '#80B0A6'

GENERAL_COLORS = [DARK_GREEN, LIGHT_GOLD, SEAGLASS, TEAL]
OCCUPATION_COLORS = [STORM, APPLE]
CAMPUS_NAMES = ['Tampa', 'St. Petersburg', 'USF Health', 'Sarasota Manatee']
OCCUPATION_NAMES = ['Student', 'Employee']
PREDICTION_COL_NAMES = ['YHAT_TAMPA', 'YHAT_ST_PETE', 'YHAT_HEALTH'] 
# 'YHAT_SARASOTA'
